ALTER TABLE students
ADD COLUMN IF NOT EXISTS "group" TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS since DATE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS allowed BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "lockAll" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS lessons JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS panels JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS exam JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS note TEXT DEFAULT '';
